### PR TITLE
[web] Integrate healthcenter register/apply

### PR DESCRIPTION
**Pull request by ZBeimnet**

### CODE REVIEW

**Review by BekyH — CHANGES_REQUESTED** [review]
I thought earlier that we said health centers apply themselves. The admin job is granting I guess. is it changed?

**Comment by ZBeimnet** [comment]
> I thought earlier that we said health centers apply themselves. The admin job is granting I guess. is it changed?

Yep, it is

**Review by Tadele01 — APPROVED** [review]

**Comment by BekyH** [comment]
> > I thought earlier that we said health centers apply themselves. The admin job is granting I guess. is it changed?
> 
> Yeah, you're right. It is not changed. Where are you seeing that logic :)
when I saw it first it seems like the admin registers them. perhaps you should rename the file

**Comment by ZBeimnet** [comment]
> > > I thought earlier that we said health centers apply themselves. The admin job is granting I guess. is it changed?
> > 
> > 
> > Yeah, you're right. It is not changed. Where are you seeing that logic :)
> > when I saw it first it seems like the admin registers them. perhaps you should rename the file

I see that may be a little confusing :). But the reason I named it admin is based on "admin's job". "healthcare/all", "healthcare/granted", "healthcare/notgranted", deleting healthcare...etc are all the function (the job) of the admin...

**Comment by BekyH** [comment]
> > > > I thought earlier that we said health centers apply themselves. The admin job is granting I guess. is it changed?
> > > 
> > > 
> > > Yeah, you're right. It is not changed. Where are you seeing that logic :)
> > > when I saw it first it seems like the admin registers them. perhaps you should rename the file
> 
> I see that may be a little confusing :). But the reason I named it admin is based on "admin's job". "healthcare/all", "healthcare/granted", "healthcare/notgranted", deleting healthcare...etc are all the function (the job) of the admin...

okay

**Comment by ZBeimnet** [comment]
> > > > I thought earlier that we said health centers apply themselves. The admin job is granting I guess. is it changed?
> > > 
> > > 
> > > Yeah, you're right. It is not changed. Where are you seeing that logic :)
> > > when I saw it first it seems like the admin registers them. perhaps you should rename the file
> 
> I see that may be a little confusing :). But the reason I named it admin is based on "admin's job". "healthcare/all", "healthcare/granted", "healthcare/notgranted", deleting healthcare...etc are all the function (the job) of the admin...

I can rename it for conformity

**Review by BekyH — APPROVED** [review]

**Pull request merged**
